#!/usr/bin/env python3
"""
generate_trends.py
Parses Warren's Trend Papers (Markdown) and generates trends.js for the public website.
"""

import re
import os
from datetime import date

TRENDS_DIR = "/Users/wittayanan/Desktop/OAT OS/oat-investment-knowledge/knowledge/trends"
OUTPUT_FILE = "/Users/wittayanan/Desktop/OAT OS/oat-public-website/trends.js"

# Display order as specified
DISPLAY_ORDER = [
    "AI-Infrastructure",
    "Memory-Supercycle",
    "Optical-Interconnect",
    "Cloud-Acceleration",
    "Custom-Silicon",
    "Agentic-AI",
    "Advanced-Packaging",
    "Semiconductor-Equipment",
    "CPU-Renaissance",
    "Power-Infrastructure",
    "Humanoid-Robots",
    "Space-Defense",
    "Defense-Materials",
    "Digital-Advertising",
]


def parse_trend_file(filepath):
    """Parse a single trend markdown file and extract structured fields."""
    tag = os.path.splitext(os.path.basename(filepath))[0]

    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()

    full_content = content

    lines = content.splitlines()

    # title: first line starting with "# "
    title = ""
    for line in lines:
        if line.startswith("# "):
            title = line[2:].strip()
            break

    # subtitle: first line that matches *...*
    subtitle = ""
    for line in lines:
        m = re.match(r"^\*(.+)\*$", line.strip())
        if m:
            subtitle = m.group(1).strip()
            break

    # conviction: from **Warren's Conviction:** ...
    conviction = ""
    m = re.search(r"\*\*Warren's Conviction:\*\*\s*(.+)", content)
    if m:
        conviction = m.group(1).strip()

    # last_updated: from **Last Updated:** ...
    last_updated = ""
    m = re.search(r"\*\*Last Updated:\*\*\s*(.+)", content)
    if m:
        last_updated = m.group(1).strip()

    # summary: first non-empty paragraph under ## ภาพรวม
    summary = ""
    overview_match = re.search(
        r"## ภาพรวม[^\n]*\n(.*?)(?=\n##|\Z)", content, re.DOTALL
    )
    if overview_match:
        overview_body = overview_match.group(1).strip()
        # Split into paragraphs and get first non-empty one
        paragraphs = [p.strip() for p in overview_body.split("\n\n") if p.strip()]
        if paragraphs:
            summary = paragraphs[0]

    # benefiting_tickers: extract **TICKER** patterns from ## หุ้นที่ได้ประโยชน์
    tickers = []
    benefiting_match = re.search(
        r"## หุ้นที่ได้ประโยชน์(.*?)(?=\n## |\Z)", content, re.DOTALL
    )
    if benefiting_match:
        benefiting_body = benefiting_match.group(1)
        # Match **TICKER** or **TICKER (...)** at start of bold patterns
        # Ticker = 1-6 uppercase letters/digits, optionally followed by space and company name in parens
        ticker_matches = re.findall(r"\*\*([A-Z]{1,6}(?:\.[A-Z])?)\b", benefiting_body)
        seen = set()
        for t in ticker_matches:
            if t not in seen:
                seen.add(t)
                tickers.append(t)

    return {
        "tag": tag,
        "title": title,
        "subtitle": subtitle,
        "conviction": conviction,
        "last_updated": last_updated,
        "summary": summary,
        "tickers": tickers,
        "full_content": full_content,
    }


def escape_for_js_template_literal(text):
    """Escape backticks and ${} sequences for use inside JS template literals."""
    text = text.replace("\\", "\\\\")
    text = text.replace("`", "\\`")
    text = text.replace("${", "\\${")
    return text


def js_string(value):
    """Wrap a value in double quotes, escaping as needed."""
    value = value.replace("\\", "\\\\")
    value = value.replace('"', '\\"')
    value = value.replace("\n", "\\n")
    return f'"{value}"'


def generate_trends_js(trends):
    today = date.today().isoformat()
    lines = []
    lines.append("// Auto-generated by generate_trends.py — do not edit manually")
    lines.append(f"// Last generated: {today}")
    lines.append("const TRENDS_DATA = [")

    for i, trend in enumerate(trends):
        escaped_content = escape_for_js_template_literal(trend["full_content"])
        tickers_js = "[" + ", ".join(f'"{t}"' for t in trend["tickers"]) + "]"

        lines.append("  {")
        lines.append(f'    tag: {js_string(trend["tag"])},')
        lines.append(f'    title: {js_string(trend["title"])},')
        lines.append(f'    subtitle: {js_string(trend["subtitle"])},')
        lines.append(f'    conviction: {js_string(trend["conviction"])},')
        lines.append(f'    last_updated: {js_string(trend["last_updated"])},')
        lines.append(f'    summary: {js_string(trend["summary"])},')
        lines.append(f'    tickers: {tickers_js},')
        lines.append(f"    content: `{escaped_content}`")
        comma = "," if i < len(trends) - 1 else ""
        lines.append(f"  }}{comma}")

    lines.append("];")
    return "\n".join(lines)


def main():
    trends = []
    missing = []

    for tag in DISPLAY_ORDER:
        filepath = os.path.join(TRENDS_DIR, f"{tag}.md")
        if not os.path.exists(filepath):
            missing.append(tag)
            print(f"  WARNING: {filepath} not found, skipping.")
            continue
        trend = parse_trend_file(filepath)
        trends.append(trend)
        print(f"  Parsed: {tag} — conviction={trend['conviction']}, tickers={trend['tickers']}")

    if missing:
        print(f"\nWARNING: {len(missing)} file(s) missing: {missing}")

    js_output = generate_trends_js(trends)

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(js_output)

    print(f"\nDone. {len(trends)} trends written to:\n  {OUTPUT_FILE}")
    print(f"File size: {os.path.getsize(OUTPUT_FILE):,} bytes")


if __name__ == "__main__":
    main()
